[package]
name = "roflcopter_snake"
version = "0.1.0"
edition = "2021"

[lib]
name = "roflcopter_snake_lib"
path = "src/lib.rs"

[[bin]]
name = "roflcopter_snake"
path = "src/main.rs"

[dependencies]
macroquad = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
